services:
  service:
    build:
      context: ./service/
      args:
        HOST_UID: ${HOST_UID:-1000}
        HOST_GID: ${HOST_GID:-1000}
        HOST_USERNAME: ${HOST_USERNAME:-user}
        HOST_GROUPNAME: ${HOST_GROUPNAME:-group}
    image: streamlit-csv-explorer:local
    environment:
      STREAMLIT_SERVER_PORT: ${STREAMLIT_SERVER_PORT:-8501}
      STREAMLIT_SERVER_ADDRESS: ${STREAMLIT_SERVER_ADDRESS:-0.0.0.0}
    ports:
      - "8501:8501"
    tty: true
    restart: unless-stopped
    volumes:
      - ./service/app:/app
      - ./service/data:/data
    command:
      - streamlit
      - run
      - /app/main.py
      - --server.address=0.0.0.0
      - --server.port=8501
      - --server.fileWatcherType=poll
      - --browser.gatherUsageStats=false
